### ISSUE TITLE
Integrate horsedrowner/SteamScreenshotManager

### ISSUE THREAD

**Issue by horsedrowner** [horsedrowner/Superscrot#36]
With a possible Dropbox-style sync thing. Set a local screenshot folder, then monitor the folder, do the SteamScreenshotManager thing and then upload them.

Two options:
1.  Specifying a custom server path (relative or absolute), then every `x` minutes, do a two-way sync;
2.  Monitoring the folder (using a file system watcher) then treat new files as if they were regularly taken screenshots. Maybe add a placeholder for the game name.

**Comment by Vivelin** [comment]
Integrating this in SSM rather than this.
